version: '3.7'

services:
  nodejs:
    image: bookstore
    build: .
    ports:
      - 9001:3000
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: A12345678
      POSTGRES_USER: postgres
      POSTGRES_DB: bookstore
